[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
optimizer_runs = 100_000

[rpc_endpoints]
base = "${BASE_MAINNET_RPC}"

[fmt]
line_length = 80
multiline_func_header = 'params_first'
